language: node_js
node_js:
    - "4.2.6"
services:
  - postgresql
script: npm test
before_script: 
    - npm install
    - psql -c 'create database dms_test;' -U postgres
after_script: cat ./coverage/lcov.info | node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage